name: 'TypeScript Deep Code Review'
description: 'Performs deep code review on TypeScript pull requests using AI'
author: 'ProjectR'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  llm-provider:
    description: 'LLM provider to use (gemini, openai, anthropic)'
    required: false
    default: 'gemini'
  llm-api-key:
    description: 'API key for the selected LLM provider'
    required: true
  llm-endpoint:
    description: 'Custom endpoint URL for the LLM API'
    required: false
  llm-model:
    description: 'Model to use for the selected provider'
    required: false
    default: 'gemini-pro'
  auto-approve:
    description: 'Whether to automatically approve PRs based on analysis'
    required: false
    default: 'true'
  auto-merge:
    description: 'Whether to automatically merge approved PRs'
    required: false
    default: 'false'
  index-cache-enabled:
    description: 'Whether to cache the indexed codebase between runs'
    required: false
    default: 'true'
  pr-number: 
    description: 'Pull request number (for manual triggering)'
    required: false
  enable-metrics:
    description: 'Whether to generate code quality metrics'
    required: false
    default: 'true'
  enable-security:
    description: 'Whether to perform security vulnerability scanning'
    required: false
    default: 'true'
  enable-performance:
    description: 'Whether to analyze code performance'
    required: false
    default: 'true'
  enable-documentation:
    description: 'Whether to check documentation completeness'
    required: false
    default: 'true'
  enable-test-coverage:
    description: 'Whether to analyze test coverage'
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'blue' 