name: 'TypeScript Deep Code Review'
description: 'Performs deep code review on TypeScript pull requests using AI'
author: 'flash'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  gemini-api-key:
    description: 'Gemini API Key'
    required: true
  gemini-model:
    description: 'Gemini model to use (e.g., gemini-2.0-flash, gemini-2.5-pro)'
    required: false
    default: 'gemini-2.0-flash'
  llm-max-tokens:
    description: 'Maximum number of tokens to use for the review'
    required: false
    default: 5000
  output-language:
    description: 'Language code for the review output (e.g., en, es, fr, de, etc.)'
    required: false
    default: 'en'
  auto-approve:
    description: 'Whether to automatically approve PRs based on analysis'
    required: false
    default: 'false'
  index-cache-enabled:
    description: 'Whether to cache the indexed codebase between runs'
    required: false
    default: 'true'
  pr-number: 
    description: 'Pull request number (for manual triggering)'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'blue' 
