name: 'TypeScript Deep Code Review'
description: 'Performs deep code review on TypeScript pull requests using AI'
author: 'ProjectR'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  llm-api-key:
    description: 'API key for the selected LLM provider'
    required: true
  llm-model:
    description: 'Gemini model to use (e.g., gemini-2.0-flash)'
    required: false
    default: 'gemini-2.0-flash'
  output-language:
    description: 'Language code for the review output (e.g., en, es, fr, de, etc.)'
    required: false
    default: 'en'
  auto-approve:
    description: 'Whether to automatically approve PRs based on analysis'
    required: false
    default: 'true'
  auto-merge:
    description: 'Whether to automatically merge approved PRs'
    required: false
    default: 'false'
  index-cache-enabled:
    description: 'Whether to cache the indexed codebase between runs'
    required: false
    default: 'true'
  pr-number: 
    description: 'Pull request number (for manual triggering)'
    required: false
  enable-metrics:
    description: 'Whether to generate code quality metrics'
    required: false
    default: 'true'
  enable-security:
    description: 'Whether to perform security vulnerability scanning'
    required: false
    default: 'true'
  enable-performance:
    description: 'Whether to analyze code performance'
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'blue' 