name: TypeScript Deep Code Review

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'Pull request number to review'
        required: true
        type: number

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build action
        run: pnpm build

      - name: TypeScript Deep Code Review
        uses: ./.
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          llm-api-key: ${{ secrets.LLM_API_KEY }}
          auto-approve: false
          auto-merge: false
          index-cache-enabled: true
          pr-number: ${{ github.event.inputs.pr-number }}
          output-language: en
          quality-threshold: 7
