name: TypeScript Deep Code Review

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'Pull request number to review'
        required: true
        type: number

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TypeScript Deep Code Review
        uses: DanielSuhett/flash@v0.0.30
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-api-key: ${{ secrets.LLM_API_KEY }}
          pr-number: ${{ github.event.inputs.pr-number }}
          output-language: en
