name: Release Action

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-bullseye
      options: --user root
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: |
          npm install -g pnpm@8.15.3
          pnpm --version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Verify build output
        run: |
          ls -la dist/
          test -f dist/index.js
          test -f dist/index.js.map

      - name: Create release package
        run: |
          mkdir -p release
          cp dist/index.js release/
          cp dist/index.js.map release/
          cp action.yml release/
          ls -la release/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/index.js
            release/index.js.map
            release/action.yml
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 